# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-31 01:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='event',
            name='tags',
            field=models.CharField(max_length=255),
        ),
    ]
