# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-12 17:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='locationreminder',
            name='position',
        ),
        migrations.AddField(
            model_name='locationreminder',
            name='latitude',
            field=models.DecimalField(decimal_places=5, default=1, max_digits=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='locationreminder',
            name='longitude',
            field=models.DecimalField(decimal_places=5, default=1, max_digits=8),
            preserve_default=False,
        ),
    ]
