# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-31 02:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20161031_0148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='end_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='location',
            field=models.IntegerField(null=True),
        ),
    ]
