# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-16 20:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20161112_1745'),
    ]

    operations = [
        migrations.AddField(
            model_name='locationreminder',
            name='description',
            field=models.CharField(default='default', max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='locationreminder',
            name='location_descriptor',
            field=models.CharField(default='default location', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='timereminder',
            name='description',
            field=models.CharField(default='default', max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='timereminder',
            name='location_descriptor',
            field=models.CharField(default='default location', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='locationreminder',
            name='end_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='locationreminder',
            name='start_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='timereminder',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
