# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-16 20:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20161116_2023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locationreminder',
            name='end_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='locationreminder',
            name='start_time',
            field=models.TimeField(),
        ),
    ]
