# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-03 18:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_group'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='users',
            new_name='user',
        ),
    ]
