# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-16 22:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20161116_2200'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='location',
        ),
        migrations.AddField(
            model_name='event',
            name='latitude',
            field=models.DecimalField(decimal_places=5, default=1, max_digits=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='longitude',
            field=models.DecimalField(decimal_places=5, default=1, max_digits=8),
            preserve_default=False,
        ),
    ]
