# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-03 18:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20161103_1853'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Group',
            new_name='MemGroup',
        ),
    ]
