# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-03 19:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20161103_1856'),
    ]

    operations = [
        migrations.RenameField(
            model_name='memgroup',
            old_name='user',
            new_name='users',
        ),
    ]
