# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-05 14:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20161104_1816'),
    ]

    operations = [
        migrations.RenameField(
            model_name='memgroup',
            old_name='users',
            new_name='admins',
        ),
    ]
