# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-05 14:17
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0010_auto_20161105_1412'),
    ]

    operations = [
        migrations.AddField(
            model_name='memgroup',
            name='subscribers',
            field=models.ManyToManyField(related_name='sub_groups', to=settings.AUTH_USER_MODEL),
        ),
    ]
